### ISSUE TITLE
Have a nicer way to manage typo in naming component

### ISSUE THREAD

**Issue by macartiant** [111StudioKK/lambda-cli#2]
Two ways for now:
- go until the end of the process and remove it with rm -rf
  OR
- ctrl c twice

**Comment by fdidron** [comment]
Temp fix, typing CTRL-C once will quit the cli without creating the components.
Still need to make it so CTRL-C goes back to the cli root instead of quitting it, related issue https://github.com/dthree/vorpal/issues/42

**Comment by fdidron** [comment]
This issue will be fixed with #7 , closing for now.
