### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by bolbovic** [111StudioKK/lambda-cli#3]
Add the generation of .gitignore with node_module in it.

**Comment by fdidron** [comment]
Quick question about this one, shouldn't we git init ?

**Comment by fdidron** [comment]
@bolbovic bump ! :)

**Comment by bolbovic** [comment]
I don't think it's necessary, it's a step we don't need specialy if we have a tool to help creating projects

**Comment by bolbovic** [comment]
What I mean by that is, we don't need to do it ourselves, lambda can do it for us

**Comment by fdidron** [comment]
I don't think this should be implemented in the cli, best way to manage this is to create a node.js project in github, it will create a .gitignore file with all the entry required for a basic node project.
Clone the repo locally then run lambda init.

.gitgnore file generated :

```
# Logs
logs
*.log
npm-debug.log*

# Runtime data
pids
*.pid
*.seed

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# node-waf configuration
.lock-wscript

# Compiled binary addons (http://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules
jspm_packages

# Optional npm cache directory
.npm

# Optional REPL history
.node_repl_history
```
