### ISSUE TITLE
Lambda-cli should provide a way to expose version number

### ISSUE THREAD

**Issue by achanehive** [111StudioKK/lambda-cli#6]
Lambda-cli should expose a version number to application. So the application has the possibility to show somewhere his version number.
A good candidate could be the version field of package.json

A way to do it:
**Config**
`new webpack.DefinePlugin({
  __VERSION__: JSON.stringify(require("./package.json").version)
})`

**App code**
`console.log(__VERSION__);`

**Comment by fdidron** [comment]
Good point, just to confirm, we should expose it on dev AND prod builds ?

**Comment by achanehive** [comment]
I think it's interesting to have it on dev and prod build to facilitate issue reporting with the version number
